name: Deploy CRTS (Nuxt) with PM2

on:
  push:
    branches:
      - Deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          bun install
      - name: prisma generate
        run: bunx prisma generate
      - name: Run tests
        run: bun run test

  call-deploy:
    needs: test
    runs-on: ["self-hosted", "WIN-F1K8J4DFM0U"]

    env:
      DEPLOY_DIR: ${{ github.ref_name == 'Deploy' && 'C:\inetpub\wwwroot\CRTS\prd'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        shell: cmd
        run: |
          del /f package-lock.json 2>nul
          bun install
      - name: prisma generate
        run: bunx prisma generate
      - name: Load SECRET_KEY from ecosystem.config.cjs
        shell: powershell
        run: |
          $secret = bun -e "console.log(require('C:/inetpub/wwwroot/CRTS/ecosystem.config.cjs').apps[0].env_production.SECRET_KEY)"
          Add-Content -Path $env:GITHUB_ENV -Value "SECRET_KEY=$secret"
      - name: Stop PM2 (Production)
        if: github.ref_name == 'Deploy'
        shell: cmd
        run: |
          cd C:\inetpub\wwwroot\CRTS
          pm2 stop CRTS
          exit /b 0
      - name: build Nuxt app
        env:
          NITRO_OUTPUT_DIR: ${{ env.DEPLOY_DIR }}
          SECRET_KEY: ${{ env.SECRET_KEY }}
        run: bun run build

  pm2_restart:
    needs: call-deploy
    runs-on: ["self-hosted", "WIN-F1K8J4DFM0U"]

    steps:
      - name: Restart PM2 (Production)
        if: github.ref_name == 'Deploy'
        shell: cmd
        run: |
          cd C:\inetpub\wwwroot\CRTS
          pm2 startOrRestart ecosystem.config.cjs --env production
          pm2 save